import type { Metadata } from "next";
import { Momo } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const poppins = ({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
 
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} min-h-screen w-full antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
